### ISSUE TITLE
Modman Installation incorrect:

### ISSUE THREAD

**Issue by paras89** [WarbyParker/Warby_MqModule#3]
There is a discrepancy in you modman file and the your app/etc/modules/Warby_Mqmodule.xml file.

The modman file pushes the code to  app/code/community/Warby/MqModule/ while your module set up file in /etc/modules expect it to be at: app/code/community/Warby/Mqmodule/

Notice the difference in Caps in MqModule and Mqmodule.

**Comment by jeffu** [comment]
Thanks @paras89, I opened a PR for this in #4.

**Comment by jeffreylo** [comment]
Thanks @paras89 and @jeffu! Merged the fix in #4.
